blank_issues_enabled: false
contact_links:
  - name: Chat mit der Community / Platz für Umsetzungsideen
    url: https://discord.gg/enn4AG3VnM
    about: Gedacht für den allgemeinen Erfahrungsaustausch. Der falsche Ort für Fehlermeldungen.
