name: Trigger builds

on: [push]

jobs:
  job_2:
    name: Build Windows Exe
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install wheel
          pip install pyinstaller
          pip install git+https://github.com/alberanid/imdbpy
          pip install -r requirements.txt
      - name: Get version
        run: |
          python feedcrawler/version.py > version.txt
          SET /p version= < version.txt
      - name: Compile Windows Exe
        run: |
          pyinstaller --onefile -y -i "feedcrawler/web/img/favicon.ico" --version-file "file_version_info.txt" --hidden-import "_rapidfuzz_cpp" --add-data "feedcrawler/web;web" "FeedCrawler.py" -n "feedcrawler-%version%-standalone-win64"
