name: Trigger builds

on: [push]

jobs:
  job_1:
    name: Build Linux wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install wheel
          pip install pyinstaller
          pip install git+https://github.com/alberanid/imdbpy
          pip install -r requirements.txt
      - name: Compile Linux wheel
        run: |
          version=$(python feedcrawler/version.py)
          python setup.py sdist bdist_wheel
      - name: Upload Linux wheel
        uses: actions/upload-artifact@v2
        with:
          name: artifact-wheel
          path: ~/dist/feedcrawler-${{ version}}-py3-none-any.whl
          
  job_2:
    name: Build Windows Exe
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install wheel
          pip install pyinstaller
          pip install git+https://github.com/alberanid/imdbpy
          pip install -r requirements.txt
      - name: Compile Windows Exe
        run: |
          $version = python feedcrawler/version.py
          pyinstaller --onefile -y -i "feedcrawler/web/img/favicon.ico" --version-file "file_version_info.txt" --hidden-import "_rapidfuzz_cpp" --add-data "feedcrawler/web;web" "FeedCrawler.py" -n "feedcrawler-$version-standalone-win64"
