name: Run Tests
on: [ pull_request ]

jobs:
  check-branch:
    name: Check version info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64
      - name: Run Version Check
        run: python .github/workflows/CheckBranch.py
  build-python:
    runs-on: ubuntu-latest
    needs: check-branch
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, "3.10", 3.11, 3.12 ]
    name: Python ${{ matrix.python-version }} build
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run build from branch
        run: python FeedCrawler.py --port=9090 --config="/home/runner/work/_temp/_github_home" --test_run --log-level=DEBUG
  build-vuejs:
    runs-on: ubuntu-latest
    needs: check-branch
    name: Node.js build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
        working-directory: feedcrawler/web_interface/vuejs_frontend
      - name: Run build from branch
        run: npm run build
        working-directory: feedcrawler/web_interface/vuejs_frontend
