name: Inactivity Bot

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 3
          days-before-issue-close: 1
          stale-issue-message: 'Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.'
          close-issue-message: 'Fehlermeldung nicht rechtzeitig aktualisiert oder kommentiert.'
          stale-issue-label: 'Inaktiv'
          close-issue-reason: 'not_planned'
          exempt-issue-labels: 'Fehler, Erweiterung'
          days-before-pr-stale: 30
          stale-pr-message: 'Pull-Request ist seit 30 Tagen inaktiv.'
          stale-pr-label: 'Inaktiv'
          operations-per-run: 99
